# Generated by Django 5.1.6 on 2025-03-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoManager", "0002_todo_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
